substitutions:
  device: "esp_svitlobot_local"
  name: "svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

packages:
  common: !include packages/common.yaml
  svitlobot: !include packages/svitlobot.yaml
  light_status: !include packages/light_status.yaml
  esp32: !include packages/esp32.yaml
  http_ota: !include packages/http_ota.yaml
